/** All design disciplines selectable across the app (signup, filters, edit-profile). */
export const disciplines: string[] = [
  "Architecture",
  "Interior",
  "Product",
  "Graphic",
  "Type & lettering",
  "Branding",
  "Illustration",
  "Photography",
  "Film & motion",
  "UX / UI",
  "Game design",
  "Fashion",
  "Textiles",
  "Jewellery",
  "Ceramics",
  "Furniture",
  "Industrial",
  "Set & exhibition",
  "Landscape",
  "Art direction",
  "3D & visualisation",
];
