INSERT INTO public.institutions (slug, name, city, country, domain, alt_domains, sso_provider, faculty_email_regex, student_email_regex, tint, initials) VALUES
('rca','Royal College of Art','London','United Kingdom','rca.ac.uk','{}','microsoft','^[a-z]+\.[a-z]+$','\d{6,}','#161514','RC'),
('csm','Central Saint Martins (UAL)','London','United Kingdom','arts.ac.uk','{"csm.arts.ac.uk"}','microsoft','^[a-z]\.[a-z]+$','\d{6,}','#161514','CS'),
('goldsmiths','Goldsmiths, University of London','London','United Kingdom','gold.ac.uk','{}','microsoft',NULL,'\d{6,}','#161514','GO'),
('gsa','Glasgow School of Art','Glasgow','United Kingdom','gsa.ac.uk','{"student.gsa.ac.uk"}','microsoft',NULL,'\d{6,}','#161514','GS'),
('parsons','Parsons School of Design (The New School)','New York','United States','newschool.edu','{}','google',NULL,'\d{6,}','#161514','PA'),
('risd','Rhode Island School of Design','Providence','United States','risd.edu','{}','google',NULL,'\d{6,}','#161514','RI'),
('pratt','Pratt Institute','Brooklyn','United States','pratt.edu','{}','google',NULL,'\d{6,}','#161514','PR'),
('sva','School of Visual Arts','New York','United States','sva.edu','{"students.sva.edu"}','google',NULL,'\d{6,}','#161514','SV'),
('cooper','The Cooper Union','New York','United States','cooper.edu','{}','google',NULL,'\d{6,}','#161514','CU'),
('mit','MIT (Architecture & Media Lab)','Cambridge, MA','United States','mit.edu','{}','microsoft',NULL,'\d{6,}','#161514','MI'),
('stanford','Stanford d.school','Stanford, CA','United States','stanford.edu','{}','google',NULL,'\d{6,}','#161514','ST'),
('cmu','Carnegie Mellon School of Design','Pittsburgh','United States','cmu.edu','{"andrew.cmu.edu"}','google',NULL,'\d{6,}','#161514','CM'),
('artcenter','ArtCenter College of Design','Pasadena','United States','artcenter.edu','{}','google',NULL,'\d{6,}','#161514','AC'),
('cca','California College of the Arts','San Francisco','United States','cca.edu','{}','google',NULL,'\d{6,}','#161514','CC'),
('calarts','CalArts','Valencia, CA','United States','calarts.edu','{}','google',NULL,'\d{6,}','#161514','CA'),
('rmit','RMIT University','Melbourne','Australia','rmit.edu.au','{"student.rmit.edu.au"}','microsoft',NULL,'\d{6,}','#161514','RM'),
('unsw','UNSW Art, Design & Architecture','Sydney','Australia','unsw.edu.au','{"ad.unsw.edu.au"}','microsoft',NULL,'\d{6,}','#161514','UN'),
('ocadu','OCAD University','Toronto','Canada','ocadu.ca','{"student.ocadu.ca"}','microsoft',NULL,'\d{6,}','#161514','OC'),
('emilycarr','Emily Carr University of Art + Design','Vancouver','Canada','ecuad.ca','{}','google',NULL,'\d{6,}','#161514','EC'),
('aalto','Aalto University','Espoo','Finland','aalto.fi','{}','microsoft',NULL,'\d{6,}','#161514','AA'),
('ecal','ECAL (University of Art and Design Lausanne)','Lausanne','Switzerland','ecal.ch','{}','microsoft',NULL,'\d{6,}','#161514','EL'),
('head','HEAD – Genève','Geneva','Switzerland','hesge.ch','{}','microsoft',NULL,'\d{6,}','#161514','HE'),
('dae','Design Academy Eindhoven','Eindhoven','Netherlands','designacademy.nl','{}','google',NULL,'\d{6,}','#161514','DA'),
('kabk','Royal Academy of Art, The Hague','The Hague','Netherlands','kabk.nl','{}','microsoft',NULL,'\d{6,}','#161514','KA'),
('polimi','Politecnico di Milano','Milan','Italy','polimi.it','{"mail.polimi.it"}','microsoft',NULL,'\d{6,}','#161514','PM'),
('naba','NABA – Nuova Accademia di Belle Arti','Milan','Italy','naba.it','{"students.naba.it"}','microsoft',NULL,'\d{6,}','#161514','NA'),
('bauhaus','Bauhaus-Universität Weimar','Weimar','Germany','uni-weimar.de','{}','microsoft',NULL,'\d{6,}','#161514','BW'),
('udk','Universität der Künste Berlin','Berlin','Germany','udk-berlin.de','{}','microsoft',NULL,'\d{6,}','#161514','UD'),
('hfg','HfG Karlsruhe','Karlsruhe','Germany','hfg-karlsruhe.de','{}','microsoft',NULL,'\d{6,}','#161514','HF'),
('ensci','ENSCI – Les Ateliers','Paris','France','ensci.com','{}','email',NULL,'\d{6,}','#161514','EN'),
('ensad','École nationale supérieure des Arts Décoratifs','Paris','France','ensad.fr','{}','microsoft',NULL,'\d{6,}','#161514','ED'),
('bezalel','Bezalel Academy of Arts and Design','Jerusalem','Israel','bezalel.ac.il','{"post.bezalel.ac.il"}','google',NULL,'\d{6,}','#161514','BE'),
('tama','Tama Art University','Tokyo','Japan','tamabi.ac.jp','{}','google',NULL,'\d{6,}','#161514','TA'),
('musashino','Musashino Art University','Tokyo','Japan','musabi.ac.jp','{}','google',NULL,'\d{6,}','#161514','MU'),
('kaist','KAIST Industrial Design','Daejeon','South Korea','kaist.ac.kr','{}','microsoft',NULL,'\d{6,}','#161514','KI'),
('hongik','Hongik University','Seoul','South Korea','hongik.ac.kr','{"mail.hongik.ac.kr"}','google',NULL,'\d{6,}','#161514','HO'),
('nid','National Institute of Design','Ahmedabad','India','nid.edu','{}','google',NULL,'\d{6,}','#161514','ND'),
('srishti','Srishti Manipal Institute','Bangalore','India','srishtimanipalinstitute.in','{}','google',NULL,'\d{6,}','#161514','SR'),
('tsinghua','Tsinghua Academy of Arts & Design','Beijing','China','tsinghua.edu.cn','{"mails.tsinghua.edu.cn"}','microsoft',NULL,'\d{6,}','#161514','TS')
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name, city = EXCLUDED.city, country = EXCLUDED.country,
  domain = EXCLUDED.domain, alt_domains = EXCLUDED.alt_domains,
  sso_provider = EXCLUDED.sso_provider,
  faculty_email_regex = EXCLUDED.faculty_email_regex,
  student_email_regex = EXCLUDED.student_email_regex;